#!/bin/bash
set -e
set -o pipefail

coro() {
  if ! [[ -d "$1" && -r "$1" && -x "$1" ]]; then
    >&2 printf '[%s] not a reachable path: `%q`\n' "${0##*/}" "$1"
    return 4
  fi
  env -C "$1" find \( -type f -o \( -type l \( -xtype f -o -xtype d \) \) \) -print0 | sed -ze 's%^\./%%' | LC_ALL=C sort -z | env -C "$1" xargs -0r stat --printf='%A\t%s\t%Y\t%N\n' -- | sed -Ene '/^.r/s%^(....)[^\t]+%\1%p'
}

if [ $# -eq 0 ]; then
  coro .
elif [ $# -eq 1 ]; then
  coro "$1"
else
  >&2 printf %s\\n "usage: ${0##*/} [rootpath]"
  false
fi
