#!/bin/sh
printf '%s\n' '#@:%{size} %{md5} %{sha1} %{sha256} *%{pathname}:'
if [ $# -gt 0 ]; then
  command hashdeep -c md5,sha1,sha256 -r -l -- "$@" | awk '/^[0-9]+,/{for(rcomma=4;rcomma;rcomma--) {if (rcomma==1) {sub(/,/," *")} else {sub(/,/," ")}}; print}' | LC_ALL=C sort -t " " -k 5,5
else
  sed -Ee 's%^\./(.)%\1%' | command hashdeep -c md5,sha1,sha256 -r -f /dev/stdin | awk '/^[0-9]+,/{for(rcomma=4;rcomma;rcomma--) {if (rcomma==1) {sub(/,/," *")} else {sub(/,/," ")}}; print}' | LC_ALL=C sort -t " " -k 5,5
fi
