#!/usr/bin/env -S bash --noprofile --norc -eo pipefail --

coro() {
  local gendreport="$(mktemp --suffix=".${0##*/}" <&-)"
  lsrmino "$@" <&- | tee -- "$gendreport" >&-
  if ! git diff --no-index --exit-code -- - "$gendreport"; then
    >&2 printf '[%s] verification failed.' "${0##*/}"
    return 1
  fi
}

if [[ -t 0 ]]; then
  >&2 printf %s\\n "usage: cat listToVerify | ${0##*/} [targets]"
  false
elif [[ $# -eq 0 ]]; then
  coro .
else
  coro "$@"
fi
